name: data_check
channels:
  - conda-forge
  - defaults

dependencies:
  - pip=22.1.2
  - pip:
      - wandb==0.12.21
      - pandas==1.4.3
      - pytest==7.1.2
      - scipy==1.8.1
      - protobuf==3.20.*
